// ==================== data.js (BẢN CHUẨN HÓA THEO GITHUB) ====================

const translations = {
    vi: {
        heroTitle: 'Gáy Khét World Cup <br/><span class="gradient-text">Nhận Thưởng Lớn</span>',
        heroDesc: 'Dự đoán kết quả từ 104 trận đấu chính thức của giải vô địch bóng đá thế giới FIFA World Cup 2026. Nhận định của bạn sẽ được lưu vĩnh viễn trên hạ tầng Walrus Blobs Storage.',
        secGroups: '<i class="fa-solid fa-users-rectangle text-walrus-aqua"></i> Cục Diện 48 Đội Đường Đến World Cup 2026',
        secMatches: '<i class="fa-regular fa-calendar-days text-worldcup-gold"></i> Lịch Trình Thi Đấu Chính Thức',
        secAi: '<i class="fa-solid fa-brain text-walrus-aqua"></i> Walrus Memory Agent',
        secPrizes: '<i class="fa-solid fa-trophy text-worldcup-gold"></i> Quỹ Giải Thưởng',
        secLeaderboard: '<i class="fa-solid fa-ranking-star text-worldcup-gold"></i> Bảng Vàng Tiên Tri',
        tabVongBang: 'Vòng Bảng', 
        tabVong32: 'Vòng 32 Đội', 
        tabVong16: 'Vòng 16 Đội', 
        tabTuKet: 'Tứ Kết', 
        tabBanKet: 'Bán Kết', 
        tabChungKet: 'Chung Kết',
        aiReading: 'Đang đọc bộ nhớ Walrus Mainnet...',
        aiWelcome: '"Chào sếp! Hãy kết nối ví Slush hoặc đăng nhập Gmail để tôi quét lịch sử gáy trận đấu của sếp trên mạng lưới Walrus nhé."',
        aiConnecting: '"Đang kết nối GitHub openfootball để tải dữ liệu lịch trình World Cup 2026 thời gian thực..."',
        aiSuccess: '"Đã đồng bộ thành công dữ liệu từ GitHub! Kết quả các trận đấu đã được cập nhật chính xác theo thời gian thực. Vào gáy tiếp đi sếp!"',
        aiFallback: '"Không kết nối được dữ liệu trực tuyến, hệ thống đang dùng dữ liệu lưu trữ dự phòng!"',
        btnGmail: 'Đăng nhập Gmail', 
        btnWallet: 'Kết nối ví Slush',
        btnHistory: 'Lịch sử dự đoán',
        prize1: '<i class="fa-solid fa-award text-yellow-500"></i> Tiên Tri Tỷ Số Đúng', 
        prize1Val: '500 WAL / Vòng',
        prize2: '<i class="fa-solid fa-face-laugh-squint text-orange-400"></i> Phân Tích Hài Hước Nhất', 
        prize2Val: '300 WAL / Trận',
        labelScore: 'Dự đoán Tỷ số', 
        labelAnalysis: 'Lý do phân tích / Câu gáy hài hước', 
        placeholderAnalysis: 'Nhập nhận định lầy lội của bạn tại đây...', 
        btnSubmit: '<i class="fa-solid fa-cloud-arrow-up"></i> Nộp Dự Đoán',
        matchUnit: 'trận', 
        resultStr: 'Kết quả'
    },
    en: {
        heroTitle: 'Roast The World Cup <br/><span class="gradient-text">Win Massive Rewards</span>',
        heroDesc: 'Predict the outcomes of all 104 official matches for the FIFA World Cup 2026. Your insights will be permanently stored on the decentralized Walrus Blobs Storage infrastructure.',
        secGroups: '<i class="fa-solid fa-users-rectangle text-walrus-aqua"></i> 48 Teams Roadmap - World Cup 2026 Groups',
        secMatches: '<i class="fa-regular fa-calendar-days text-worldcup-gold"></i> Official Match Schedule',
        secAi: '<i class="fa-solid fa-brain text-walrus-aqua"></i> Walrus Memory Agent',
        secPrizes: '<i class="fa-solid fa-trophy text-worldcup-gold"></i> Prize Pool & Rewards',
        secLeaderboard: '<i class="fa-solid fa-ranking-star text-worldcup-gold"></i> Prediction Leaderboard',
        tabVongBang: 'Group Stage', 
        tabVong32: 'Round of 32', 
        tabVong16: 'Round of 16', 
        tabTuKet: 'Quarter-Finals', 
        tabBanKet: 'Semi-Finals', 
        tabChungKet: 'Finals',
        aiReading: 'Reading Walrus Mainnet storage...',
        aiWelcome: '"Hello boss! Connect your Slush Wallet or sign in with Gmail so I can scan your historical prediction logs on the Walrus Network."',
        aiConnecting: '"Connecting to GitHub openfootball API to fetch live World Cup 2026 results..."',
        aiSuccess: '"Data sync successful! Real-time configurations and scores updated via GitHub. Let the roasted games begin!"',
        aiFallback: '"External data offline, actively recovering tournament state from backup storage!"',
        btnGmail: 'Sign in with Gmail', 
        btnWallet: 'Connect Slush Wallet',
        btnHistory: 'Prediction History',
        prize1: '<i class="fa-solid fa-award text-yellow-500"></i> Correct Score Predictor', 
        prize1Val: '500 WAL / Round',
        prize2: '<i class="fa-solid fa-face-laugh-squint text-orange-400"></i> Funniest Match Analyst', 
        prize2Val: '300 WAL / Match',
        labelScore: 'Score Prediction', 
        labelAnalysis: 'Analysis / Banter Comment', 
        placeholderAnalysis: 'Type your funny, trash-talk prediction here...', 
        btnSubmit: '<i class="fa-solid fa-cloud-arrow-up"></i> Submit Prediction',
        matchUnit: 'matches', 
        resultStr: 'Result'
    }
};

// Từ điển Map chuẩn theo chính xác chuỗi kí tự của openfootball JSON (Fix hoàn toàn lỗi lệch tên)
const countryMap = {
    "Mexico": { vi: "Mexico", code: "mx" },
    "South Africa": { vi: "Nam Phi", code: "za" },
    "South Korea": { vi: "Hàn Quốc", code: "kr" },
    "Czechia": { vi: "CH Séc", code: "cz" },
    "Canada": { vi: "Canada", code: "ca" },
    "Bosnia/Herzeg.": { vi: "Bosnia/Herzeg.", code: "ba" },
    "Qatar": { vi: "Qatar", code: "qa" },
    "Switzerland": { vi: "Thụy Sĩ", code: "ch" },
    "Brazil": { vi: "Brazil", code: "br" },
    "Morocco": { vi: "Ma Rốc", code: "ma" },
    "Haiti": { vi: "Haiti", code: "ht" },
    "Scotland": { vi: "Scotland", code: "gb-sct" },
    "United States": { vi: "Mỹ", code: "us" },
    "Paraguay": { vi: "Paraguay", code: "py" },
    "Australia": { vi: "Úc", code: "au" },
    "Turkey": { vi: "Thổ Nhĩ Kỳ", code: "tr" },
    "Germany": { vi: "Đức", code: "de" },
    "Curaçao": { vi: "Curacao", code: "cw" },
    "Ivory Coast": { vi: "Bờ Biển Ngà", code: "ci" },
    "Ecuador": { vi: "Ecuador", code: "ec" },
    "Netherlands": { vi: "Hà Lan", code: "nl" },
    "Japan": { vi: "Nhật Bản", code: "jp" },
    "Sweden": { vi: "Thụy Điển", code: "se" },
    "Tunisia": { vi: "Tunisia", code: "tn" },
    "Belgium": { vi: "Bỉ", code: "be" },
    "Egypt": { vi: "Ai Cập", code: "eg" },
    "Iran": { vi: "Iran", code: "ir" },
    "New Zealand": { vi: "New Zealand", code: "nz" },
    "Spain": { vi: "Tây Ban Nha", code: "es" },
    "Cape Verde": { vi: "Cape Verde", code: "cv" },
    "Saudi Arabia": { vi: "Ả Rập Xê Út", code: "sa" },
    "Uruguay": { vi: "Uruguay", code: "uy" },
    "France": { vi: "Pháp", code: "fr" },
    "Senegal": { vi: "Senegal", code: "sn" },
    "Iraq": { vi: "Iraq", code: "iq" },
    "Norway": { vi: "Na Uy", code: "no" },
    "Argentina": { vi: "Argentina", code: "ar" },
    "Algeria": { vi: "Algeria", code: "dz" },
    "Austria": { vi: "Áo", code: "at" },
    "Jordan": { vi: "Jordan", code: "jo" },
    "Portugal": { vi: "Bồ Đào Nha", code: "pt" },
    "Congo": { vi: "Congo", code: "cg" },
    "Uzbekistan": { vi: "Uzbekistan", code: "uz" },
    "Colombia": { vi: "Colombia", code: "co" },
    "England": { vi: "Anh", code: "gb-eng" },
    "Croatia": { vi: "Croatia", code: "hr" },
    "Ghana": { vi: "Ghana", code: "gh" },
    "Panama": { vi: "Panama", code: "pa" }
};

let officialMatches = [];
let worldCupGroups = {};

const mockLeaderboard = [
    { name: "TayBew", score: 1240, countryCode: "vn" },
    { name: "HALN", score: 1180, countryCode: "vn" },
    { name: "Jack", score: 1090, countryCode: "us" },
    { name: "Puchi", score: 980, countryCode: "br" },
    { name: "Stravia", score: 920, countryCode: "th" }
];
