// data.js

const translations = {
    vi: {
        heroTitle: 'Gáy Khét World Cup <br/><span class="gradient-text">Nhận Thưởng Lớn</span>',
        heroDesc: 'Dự đoán kết quả từ 104 trận đấu chính thức của giải vô địch bóng đá thế giới FIFA World Cup 2026. Nhận định của bạn sẽ được lưu vĩnh viễn trên hạ tầng Walrus Blobs Storage.',
        secGroups: '<i class="fa-solid fa-users-rectangle text-walrus-aqua"></i> Cục Diện 48 Đội Đường Đến World Cup 2026',
        secMatches: '<i class="fa-regular fa-calendar-days text-worldcup-gold"></i> Lịch Trình Thi Đấu Chính Thức',
        secAi: '<i class="fa-solid fa-brain text-walrus-aqua"></i> Walrus Memory Agent',
        secPrizes: '<i class="fa-solid fa-trophy text-worldcup-gold"></i> Quỹ Giải Thưởng',
        secLeaderboard: '<i class="fa-solid fa-ranking-star text-worldcup-gold"></i> Bảng Vàng Tiên Tri',
        tabVongBang: 'Vòng Bảng', 
        tabVong32: 'Vòng 32 Đội', 
        tabVong16: 'Vòng 16 Đội', 
        tabTuKet: 'Tứ Kết', 
        tabBanKet: 'Bán Kết', 
        tabChungKet: 'Chung Kết',
        aiReading: 'Đang đọc bộ nhớ Walrus Mainnet...',
        aiWelcome: '"Chào sếp! Hãy kết nối ví Slush hoặc đăng nhập Gmail để tôi quét lịch sử gáy trận đấu của sếp trên mạng lưới Walrus nhé."',
        aiConnecting: '"Đang kết nối API football-data.org để lấy kết quả World Cup 2026 thời gian thực..."',
        aiSuccess: '"Đã đồng bộ thành công dữ liệu từ FIFA! Sơ đồ Vòng 32 Đội và kết quả các trận đấu đã được cập nhật chính xác theo thời gian thực. Vào gáy tiếp đi sếp!"',
        aiFallback: '"Không kết nối được API bên ngoài, tôi đang sử dụng dữ liệu bộ nhớ dự phòng có sẵn trên mạng lưới Walrus cho sếp nhé!"',
        btnGmail: 'Đăng nhập Gmail', 
        btnWallet: 'Kết nối ví Slush',
        btnHistory: 'Lịch sử dự đoán',
        prize1: '<i class="fa-solid fa-award text-yellow-500"></i> Tiên Tri Tỷ Số Đúng', 
        prize1Val: '500 WAL / Vòng',
        prize2: '<i class="fa-solid fa-face-laugh-squint text-orange-400"></i> Phân Tích Hài Hước Nhất', 
        prize2Val: '300 WAL / Trận',
        labelScore: 'Dự đoán Tỷ số', 
        labelAnalysis: 'Lý do phân tích / Câu gáy hài hước', 
        placeholderAnalysis: 'Nhập nhận định lầy lội của bạn tại đây...', 
        btnSubmit: '<i class="fa-solid fa-cloud-arrow-up"></i> Nộp Dự Đoán',
        matchUnit: 'trận', 
        resultStr: 'Kết quả'
    },
    en: {
        heroTitle: 'Roast The World Cup <br/><span class="gradient-text">Win Massive Rewards</span>',
        heroDesc: 'Predict the outcomes of all 104 official matches for the FIFA World Cup 2026. Your insights will be permanently stored on the decentralized Walrus Blobs Storage infrastructure.',
        secGroups: '<i class="fa-solid fa-users-rectangle text-walrus-aqua"></i> 48 Teams Roadmap - World Cup 2026 Groups',
        secMatches: '<i class="fa-regular fa-calendar-days text-worldcup-gold"></i> Official Match Schedule',
        secAi: '<i class="fa-solid fa-brain text-walrus-aqua"></i> Walrus Memory Agent',
        secPrizes: '<i class="fa-solid fa-trophy text-worldcup-gold"></i> Prize Pool & Rewards',
        secLeaderboard: '<i class="fa-solid fa-ranking-star text-worldcup-gold"></i> Prediction Leaderboard',
        tabVongBang: 'Group Stage', 
        tabVong32: 'Round of 32', 
        tabVong16: 'Round of 16', 
        tabTuKet: 'Quarter-Finals', 
        tabBanKet: 'Semi-Finals', 
        tabChungKet: 'Finals',
        aiReading: 'Reading Walrus Mainnet storage...',
        aiWelcome: '"Hello boss! Connect your Slush Wallet or sign in with Gmail so I can scan your historical prediction logs on the Walrus Network."',
        aiConnecting: '"Connecting to football-data.org API to fetch live World Cup 2026 results in real-time..."',
        aiSuccess: '"FIFA data sync successful! Round of 32 configurations and real-time scores updated via Walrus Memory. Let the roasted games begin!"',
        aiFallback: '"External API offline, I am actively recovering backup tournament state from the secure Walrus decentralized nodes!"',
        btnGmail: 'Sign in with Gmail', 
        btnWallet: 'Connect Slush Wallet',
        btnHistory: 'Prediction History',
        prize1: '<i class="fa-solid fa-award text-yellow-500"></i> Correct Score Predictor', 
        prize1Val: '500 WAL / Round',
        prize2: '<i class="fa-solid fa-face-laugh-squint text-orange-400"></i> Funniest Match Analyst', 
        prize2Val: '300 WAL / Match',
        labelScore: 'Score Prediction', 
        labelAnalysis: 'Analysis / Banter Comment', 
        placeholderAnalysis: 'Type your funny, trash-talk prediction here...', 
        btnSubmit: '<i class="fa-solid fa-cloud-arrow-up"></i> Submit Prediction',
        matchUnit: 'matches', 
        resultStr: 'Result'
    }
};

const worldCupGroups = {
    "Bảng A": [{ name: "Mexico", nameEn: "Mexico", code: "mx" }, { name: "Nam Phi", nameEn: "South Africa", code: "za" }, { name: "Hàn Quốc", nameEn: "South Korea", code: "kr" }, { name: "CH Séc", nameEn: "Czech Republic", code: "cz" }],
    "Bảng B": [{ name: "Canada", nameEn: "Canada", code: "ca" }, { name: "Bosnia/Herzeg.", nameEn: "Bosnia/Herzeg.", code: "ba" }, { name: "Qatar", nameEn: "Qatar", code: "qa" }, { name: "Thụy Sĩ", nameEn: "Switzerland", code: "ch" }],
    "Bảng C": [{ name: "Brazil", nameEn: "Brazil", code: "br" }, { name: "Ma Rốc", nameEn: "Morocco", code: "ma" }, { name: "Haiti", nameEn: "Haiti", code: "ht" }, { name: "Scotland", nameEn: "Scotland", code: "gb-sct" }],
    "Bảng D": [{ name: "Mỹ", nameEn: "USA", code: "us" }, { name: "Paraguay", nameEn: "Paraguay", code: "py" }, { name: "Úc", nameEn: "Australia", code: "au" }, { name: "Thổ Nhĩ Kỳ", nameEn: "Turkey", code: "tr" }],
    "Bảng E": [{ name: "Đức", nameEn: "Germany", code: "de" }, { name: "Curacao", nameEn: "Curacao", code: "cw" }, { name: "Bờ Biển Ngà", nameEn: "Ivory Coast", code: "ci" }, { name: "Ecuador", nameEn: "Ecuador", code: "ec" }],
    "Bảng F": [{ name: "Hà Lan", nameEn: "Netherlands", code: "nl" }, { name: "Nhật Bản", nameEn: "Japan", code: "jp" }, { name: "Thụy Điển", nameEn: "Sweden", code: "se" }, { name: "Tunisia", nameEn: "Tunisia", code: "tn" }],
    "Bảng G": [{ name: "Bỉ", nameEn: "Belgium", code: "be" }, { name: "Ai Cập", nameEn: "Egypt", code: "eg" }, { name: "Iran", nameEn: "Iran", code: "ir" }, { name: "New Zealand", nameEn: "New Zealand", code: "nz" }],
    "Bảng H": [{ name: "Tây Ban Nha", nameEn: "Spain", code: "es" }, { name: "Cape Verde", nameEn: "Cape Verde", code: "cv" }, { name: "Ả Rập Xê Út", nameEn: "Saudi Arabia", code: "sa" }, { name: "Uruguay", nameEn: "Uruguay", code: "uy" }],
    "Bảng I": [{ name: "Pháp", nameEn: "France", code: "fr" }, { name: "Senegal", nameEn: "Senegal", code: "sn" }, { name: "Iraq", nameEn: "Iraq", code: "iq" }, { name: "Na Uy", nameEn: "Norway", code: "no" }],
    "Bảng J": [{ name: "Argentina", nameEn: "Argentina", code: "ar" }, { name: "Algeria", nameEn: "Algeria", code: "dz" }, { name: "Áo", nameEn: "Austria", code: "at" }, { name: "Jordan", nameEn: "Jordan", code: "jo" }],
    "Bảng K": [{ name: "Bồ Đào Nha", nameEn: "Portugal", code: "pt" }, { name: "Congo", nameEn: "Congo", code: "cg" }, { name: "Uzbekistan", nameEn: "Uzbekistan", code: "uz" }, { name: "Colombia", nameEn: "Colombia", code: "co" }],
    "Bảng L": [{ name: "Anh", nameEn: "England", code: "gb-eng" }, { name: "Croatia", nameEn: "Croatia", code: "hr" }, { name: "Ghana", nameEn: "Ghana", code: "gh" }, { name: "Panama", nameEn: "Panama", code: "pa" }]
};

const officialMatches = [
    { id: "1", group: "Bảng A", groupEn: "Group A", date: "Thứ 6, 12/06/2026", time: "2:00", stadium: "Mexico City Stadium", teamA: "Mexico", teamAEn: "Mexico", codeA: "mx", teamB: "Nam Phi", teamBEn: "South Africa", codeB: "za", type: "vong-bang", isHot: true },
    { id: "2", group: "Bảng A", groupEn: "Group A", date: "Thứ 6, 12/06/2026", time: "9:00", stadium: "Guadalajara Stadium", teamA: "Hàn Quốc", teamAEn: "South Korea", codeA: "kr", teamB: "CH Séc", teamBEn: "Czech Republic", codeB: "cz", type: "vong-bang" },
    { id: "3", group: "Bảng B", groupEn: "Group B", date: "Thứ 7, 13/06/2026", time: "2:00", stadium: "Toronto Stadium", teamA: "Canada", teamAEn: "Canada", codeA: "ca", teamB: "Bosnia/Herzeg.", teamBEn: "Bosnia/Herzeg.", codeB: "ba", type: "vong-bang" },
    { id: "4", group: "Bảng D", groupEn: "Group D", date: "Thứ 7, 13/06/2026", time: "8:00", stadium: "Los Angeles Stadium", teamA: "Mỹ", teamAEn: "USA", codeA: "us", teamB: "Paraguay", teamBEn: "Paraguay", codeB: "py", type: "vong-bang", isHot: true },
    { id: "5", group: "Bảng C", groupEn: "Group C", date: "CN, 14/06/2026", time: "8:00", stadium: "Boston Stadium", teamA: "Haiti", teamAEn: "Haiti", codeA: "ht", teamB: "Scotland", teamBEn: "Scotland", codeB: "gb-sct", type: "vong-bang" },
    { id: "6", group: "Bảng D", groupEn: "Group D", date: "CN, 14/06/2026", time: "11:00", stadium: "Vancouver Stadium", teamA: "Australia", teamAEn: "Australia", codeA: "au", teamB: "Thổ Nhĩ Kỳ", teamBEn: "Turkey", codeB: "tr", type: "vong-bang" },
    { id: "7", group: "Bảng C", groupEn: "Group C", date: "CN, 14/06/2026", time: "5:00", stadium: "New York/New Jersey Stadium", teamA: "Brazil", teamAEn: "Brazil", codeA: "br", teamB: "Ma Rốc", teamBEn: "Morocco", codeB: "ma", type: "vong-bang", isHot: true },
    { id: "8", group: "Bảng B", groupEn: "Group B", date: "CN, 14/06/2026", time: "2:00", stadium: "San Francisco Bay Area Stadium", teamA: "Qatar", teamAEn: "Qatar", codeA: "qa", teamB: "Thụy Sĩ", teamBEn: "Switzerland", codeB: "ch", type: "vong-bang" },
    { id: "9", group: "Bảng E", groupEn: "Group E", date: "Thứ 2, 15/06/2026", time: "6:00", stadium: "Philadelphia Stadium", teamA: "Bờ Biển Ngà", teamAEn: "Ivory Coast", codeA: "ci", teamB: "Ecuador", teamBEn: "Ecuador", codeB: "ec", type: "vong-bang" },
    { id: "10", group: "Bảng E", groupEn: "Group E", date: "Thứ 2, 15/06/2026", time: "0:00", stadium: "Houston Stadium", teamA: "Đức", teamAEn: "Germany", codeA: "de", teamB: "Curacao", teamBEn: "Curacao", codeB: "cw", type: "vong-bang" },
    { id: "11", group: "Bảng F", groupEn: "Group F", date: "Thứ 2, 15/06/2026", time: "3:00", stadium: "Dallas Stadium", teamA: "Hà Lan", teamAEn: "Netherlands", codeA: "nl", teamB: "Nhật Bản", teamBEn: "Japan", codeB: "jp", type: "vong-bang", isHot: true },
    { id: "12", group: "Bảng F", groupEn: "Group F", date: "Thứ 2, 15/06/2026", time: "9:00", stadium: "Monterrey Stadium", teamA: "Thụy Điển", teamAEn: "Sweden", codeA: "se", teamB: "Tunisia", teamBEn: "Tunisia", codeB: "tn", type: "vong-bang" },
    { id: "13", group: "Bảng H", groupEn: "Group H", date: "Thứ 3, 16/06/2026", time: "5:00", stadium: "Miami Stadium", teamA: "Ả Rập Xê Út", teamAEn: "Saudi Arabia", codeA: "sa", teamB: "Uruguay", teamBEn: "Uruguay", codeB: "uy", type: "vong-bang" },
    { id: "14", group: "Bảng H", groupEn: "Group H", date: "Thứ 2, 15/06/2026", time: "23:00", stadium: "Atlanta Stadium", teamA: "Tây Ban Nha", teamAEn: "Spain", codeA: "es", teamB: "Cape Verde", teamBEn: "Cape Verde", codeB: "cv", type: "vong-bang" },
    { id: "15", group: "Bảng G", groupEn: "Group G", date: "Thứ 3, 16/06/2026", time: "8:00", stadium: "Los Angeles Stadium", teamA: "Iran", teamAEn: "Iran", codeA: "ir", teamB: "New Zealand", teamBEn: "New Zealand", codeB: "nz", type: "vong-bang" },
    { id: "16", group: "Bảng G", groupEn: "Group G", date: "Thứ 3, 16/06/2026", time: "2:00", stadium: "Seattle Stadium", teamA: "Bỉ", teamAEn: "Belgium", codeA: "be", teamB: "Ai Cập", teamBEn: "Egypt", codeB: "eg", type: "vong-bang" },
    { id: "17", group: "Bảng I", groupEn: "Group I", date: "Thứ 4, 17/06/2026", time: "2:00", stadium: "New York/New Jersey Stadium", teamA: "Pháp", teamAEn: "France", codeA: "fr", teamB: "Senegal", teamBEn: "Senegal", codeB: "sn", type: "vong-bang", isHot: true },
    { id: "18", group: "Bảng I", groupEn: "Group I", date: "Thứ 4, 17/06/2026", time: "5:00", stadium: "Boston Stadium", teamA: "Iraq", teamAEn: "Iraq", codeA: "iq", teamB: "Na Uy", teamBEn: "Norway", codeB: "no", type: "vong-bang" },
    { id: "19", group: "Bảng J", groupEn: "Group J", date: "Thứ 4, 17/06/2026", time: "8:00", stadium: "Kansas City Stadium", teamA: "Argentina", teamAEn: "Argentina", codeA: "ar", teamB: "Algeria", teamBEn: "Algeria", codeB: "dz", type: "vong-bang", isHot: true },
    { id: "20", group: "Bảng J", groupEn: "Group J", date: "Thứ 4, 17/06/2026", time: "11:00", stadium: "San Francisco Bay Area Stadium", teamA: "Áo", teamAEn: "Austria", codeA: "at", teamB: "Jordan", teamBEn: "Jordan", codeB: "jo", type: "vong-bang" },
    { id: "21", group: "Bảng L", groupEn: "Group L", date: "Thứ 5, 18/06/2026", time: "6:00", stadium: "Toronto Stadium", teamA: "Ghana", teamAEn: "Ghana", codeA: "gh", teamB: "Panama", teamBEn: "Panama", codeB: "pa", type: "vong-bang" },
    { id: "22", group: "Bảng L", groupEn: "Group L", date: "Thứ 5, 18/06/2026", time: "3:00", stadium: "Dallas Stadium", teamA: "Anh", teamAEn: "England", codeA: "gb-eng", teamB: "Croatia", teamBEn: "Croatia", codeB: "hr", type: "vong-bang", isHot: true },
    { id: "23", group: "Bảng K", groupEn: "Group K", date: "Thứ 5, 18/06/2026", time: "0:00", stadium: "Houston Stadium", teamA: "Bồ Đào Nha", teamAEn: "Portugal", codeA: "pt", teamB: "Congo", teamBEn: "Congo", codeB: "cg", type: "vong-bang" },
    { id: "24", group: "Bảng K", groupEn: "Group K", date: "Thứ 5, 18/06/2026", time: "9:00", stadium: "Mexico City Stadium", teamA: "Uzbekistan", teamAEn: "Uzbekistan", codeA: "uz", teamB: "Colombia", teamBEn: "Colombia", codeB: "co", type: "vong-bang" },
    { id: "25", group: "Bảng A", groupEn: "Group A", date: "Thứ 5, 18/06/2026", time: "23:00", stadium: "Atlanta Stadium", teamA: "CH Séc", teamAEn: "Czech Republic", codeA: "cz", teamB: "Nam Phi", teamBEn: "South Africa", codeB: "za", type: "vong-bang" },
    { id: "26", group: "Bảng B", groupEn: "Group B", date: "Thứ 6, 19/06/2026", time: "2:00", stadium: "Los Angeles Stadium", teamA: "Thụy Sĩ", teamAEn: "Switzerland", codeA: "ch", teamB: "Bosnia/Herzeg.", teamBEn: "Bosnia/Herzeg.", codeB: "ba", type: "vong-bang" },
    { id: "27", group: "Bảng B", groupEn: "Group B", date: "Thứ 6, 19/06/2026", time: "5:00", stadium: "Vancouver Stadium", teamA: "Canada", teamAEn: "Canada", codeA: "ca", teamB: "Qatar", teamBEn: "Qatar", codeB: "qa", type: "vong-bang" },
    { id: "28", group: "Bảng A", groupEn: "Group A", date: "Thứ 6, 19/06/2026", time: "8:00", stadium: "Guadalajara Stadium", teamA: "Mexico", teamAEn: "Mexico", codeA: "mx", teamB: "Hàn Quốc", teamBEn: "South Korea", codeB: "kr", type: "vong-bang" },
    { id: "29", group: "Bảng C", groupEn: "Group C", date: "Thứ 7, 20/06/2026", time: "7:30", stadium: "Philadelphia Stadium", teamA: "Brazil", teamAEn: "Brazil", codeA: "br", teamB: "Haiti", teamBEn: "Haiti", codeB: "ht", type: "vong-bang" },
    { id: "30", group: "Bảng C", groupEn: "Group C", date: "Thứ 7, 20/06/2026", time: "5:00", stadium: "Boston Stadium", teamA: "Scotland", teamAEn: "Scotland", codeA: "gb-sct", teamB: "Ma Rốc", teamBEn: "Morocco", codeB: "ma", type: "vong-bang" },
    { id: "31", group: "Bảng D", groupEn: "Group D", date: "Thứ 7, 20/06/2026", time: "10:00", stadium: "San Francisco Bay Area Stadium", teamA: "Thổ Nhĩ Kỳ", teamAEn: "Turkey", codeA: "tr", teamB: "Paraguay", teamBEn: "Paraguay", codeB: "py", type: "vong-bang" },
    { id: "32", group: "Bảng D", groupEn: "Group D", date: "Thứ 7, 20/06/2026", time: "2:00", stadium: "Seattle Stadium", teamA: "Mỹ", teamAEn: "USA", codeA: "us", teamB: "Australia", teamBEn: "Australia", codeB: "au", type: "vong-bang" },
    { id: "33", group: "Bảng E", groupEn: "Group E", date: "CN, 21/06/2026", time: "3:00", stadium: "Toronto Stadium", teamA: "Đức", teamAEn: "Germany", codeA: "de", teamB: "Bờ Biển Ngà", teamBEn: "Ivory Coast", codeB: "ci", type: "vong-bang" },
    { id: "34", group: "Bảng E", groupEn: "Group E", date: "CN, 21/06/2026", time: "7:00", stadium: "Kansas City Stadium", teamA: "Ecuador", teamAEn: "Ecuador", codeA: "ec", teamB: "Curacao", teamBEn: "Curacao", codeB: "cw", type: "vong-bang" },
    { id: "35", group: "Bảng F", groupEn: "Group F", date: "CN, 21/06/2026", time: "0:00", stadium: "Houston Stadium", teamA: "Hà Lan", teamAEn: "Netherlands", codeA: "nl", teamB: "Thụy Điển", teamBEn: "Sweden", codeB: "se", type: "vong-bang" },
    { id: "36", group: "Bảng F", groupEn: "Group F", date: "CN, 21/06/2026", time: "11:00", stadium: "Monterrey Stadium", teamA: "Tunisia", teamAEn: "Tunisia", codeA: "tn", teamB: "Nhật Bản", teamBEn: "Japan", codeB: "jp", type: "vong-bang" },
    { id: "37", group: "Bảng H", groupEn: "Group H", date: "Thứ 2, 22/06/2026", time: "5:00", stadium: "Miami Stadium", teamA: "Uruguay", teamAEn: "Uruguay", codeA: "uy", teamB: "Cape Verde", teamBEn: "Cape Verde", codeB: "cv", type: "vong-bang" },
    { id: "38", group: "Bảng H", groupEn: "Group H", date: "CN, 21/06/2026", time: "23:00", stadium: "Atlanta Stadium", teamA: "Tây Ban Nha", teamAEn: "Spain", codeA: "es", teamB: "Ả Rập Xê Út", teamBEn: "Saudi Arabia", codeB: "sa", type: "vong-bang" },
    { id: "39", group: "Bảng G", groupEn: "Group G", date: "Thứ 2, 22/06/2026", time: "2:00", stadium: "Los Angeles Stadium", teamA: "Bỉ", teamAEn: "Belgium", codeA: "be", teamB: "Iran", teamBEn: "Iran", codeB: "ir", type: "vong-bang" },
    { id: "40", group: "Bảng G", groupEn: "Group G", date: "Thứ 2, 22/06/2026", time: "11:00", stadium: "Vancouver Stadium", teamA: "New Zealand", teamAEn: "New Zealand", codeA: "nz", teamB: "Ai Cập", teamBEn: "Egypt", codeB: "eg", type: "vong-bang" },
    { id: "41", group: "Bảng I", groupEn: "Group I", date: "Thứ 3, 23/06/2026", time: "7:00", stadium: "New York/New Jersey Stadium", teamA: "Na Uy", teamAEn: "Norway", codeA: "no", teamB: "Senegal", teamBEn: "Senegal", codeB: "sn", type: "vong-bang" },
    { id: "42", group: "Bảng I", groupEn: "Group I", date: "Thứ 3, 23/06/2026", time: "4:00", stadium: "Philadelphia Stadium", teamA: "Pháp", teamAEn: "France", codeA: "fr", teamB: "Iraq", teamBEn: "Iraq", codeB: "iq", type: "vong-bang" },
    { id: "44", group: "Bảng J", groupEn: "Group J", date: "Thứ 3, 23/06/2026", time: "10:00", stadium: "San Francisco Bay Area Stadium", teamA: "Jordan", teamAEn: "Jordan", codeA: "jo", teamB: "Algeria", teamBEn: "Algeria", codeB: "dz", type: "vong-bang" },
    { id: "43", group: "Bảng J", groupEn: "Group J", date: "Thứ 3, 23/06/2026", time: "0:00", stadium: "Dallas Stadium", teamA: "Argentina", teamAEn: "Argentina", codeA: "ar", teamB: "Áo", teamBEn: "Austria", codeB: "at", type: "vong-bang" },
    { id: "45", group: "Bảng L", groupEn: "Group L", date: "Thứ 4, 24/06/2026", time: "3:00", stadium: "Boston Stadium", teamA: "Anh", teamAEn: "England", codeA: "gb-eng", teamB: "Ghana", teamBEn: "Ghana", codeB: "gh", type: "vong-bang" },
    { id: "46", group: "Bảng L", groupEn: "Group L", date: "Thứ 4, 24/06/2026", time: "6:00", stadium: "Toronto Stadium", teamA: "Panama", teamAEn: "Panama", codeA: "pa", teamB: "Croatia", teamBEn: "Croatia", codeB: "hr", type: "vong-bang" },
    { id: "47", group: "Bảng K", groupEn: "Group K", date: "Thứ 4, 24/06/2026", time: "0:00", stadium: "Houston Stadium", teamA: "Bồ Đào Nha", teamAEn: "Portugal", codeA: "pt", teamB: "Colombia", teamBEn: "Colombia", codeB: "co", type: "vong-bang" },
    { id: "48", group: "Bảng K", groupEn: "Group K", date: "Thứ 4, 24/06/2026", time: "9:00", stadium: "Guadalajara Stadium", teamA: "Colombia", teamAEn: "Colombia", codeA: "co", teamB: "Congo", teamBEn: "Congo", codeB: "cg", type: "vong-bang" },
    { id: "49", group: "Bảng C", groupEn: "Group C", date: "Thứ 5, 25/06/2026", time: "5:00", stadium: "Miami Stadium", teamA: "Scotland", teamAEn: "Scotland", codeA: "gb-sct", teamB: "Brazil", teamBEn: "Brazil", codeB: "br", type: "vong-bang" },
    { id: "50", group: "Bảng C", groupEn: "Group C", date: "Thứ 5, 25/06/2026", time: "5:00", stadium: "Atlanta Stadium", teamA: "Ma Rốc", teamAEn: "Morocco", codeA: "ma", teamB: "Haiti", teamBEn: "Haiti", codeB: "ht", type: "vong-bang" },
    { id: "51", group: "Bảng B", groupEn: "Group B", date: "Thứ 5, 25/06/2026", time: "2:00", stadium: "Vancouver Stadium", teamA: "Thụy Sĩ", teamAEn: "Switzerland", codeA: "ch", teamB: "Canada", teamBEn: "Canada", codeB: "ca", type: "vong-bang" },
    { id: "52", group: "Bảng B", groupEn: "Group B", date: "Thứ 5, 25/06/2026", time: "2:00", stadium: "Seattle Stadium", teamA: "Bosnia/Herzeg.", teamAEn: "Bosnia/Herzeg.", codeA: "ba", teamB: "Qatar", teamBEn: "Qatar", codeB: "qa", type: "vong-bang" },
    { id: "53", group: "Bảng A", groupEn: "Group A", date: "Thứ 5, 25/06/2026", time: "8:00", stadium: "Mexico City Stadium", teamA: "CH Séc", teamAEn: "Czech Republic", codeA: "cz", teamB: "Mexico", teamBEn: "Mexico", codeB: "mx", type: "vong-bang" },
    { id: "54", group: "Bảng A", groupEn: "Group A", date: "Thứ 5, 25/06/2026", time: "8:00", stadium: "Monterrey Stadium", teamA: "Nam Phi", teamAEn: "South Africa", codeA: "za", teamB: "Hàn Quốc", teamBEn: "South Korea", codeB: "kr", type: "vong-bang" },
    { id: "55", group: "Bảng E", groupEn: "Group E", date: "Thứ 6, 26/06/2026", time: "3:00", stadium: "Philadelphia Stadium", teamA: "Curacao", teamAEn: "Curacao", codeA: "cw", teamB: "Bờ Biển Ngà", teamBEn: "Ivory Coast", codeB: "ci", type: "vong-bang" },
    { id: "56", group: "Bảng E", groupEn: "Group E", date: "Thứ 6, 26/06/2026", time: "3:00", stadium: "New York/New Jersey Stadium", teamA: "Ecuador", teamAEn: "Ecuador", codeA: "ec", teamB: "Đức", teamAEn: "Germany", codeB: "de", type: "vong-bang" },
    { id: "57", group: "Bảng F", groupEn: "Group F", date: "Thứ 6, 26/06/2026", time: "6:00", stadium: "Dallas Stadium", teamA: "Nhật Bản", teamAEn: "Japan", codeA: "jp", teamB: "Thụy Điển", teamBEn: "Sweden", codeB: "se", type: "vong-bang" },
    { id: "58", group: "Bảng F", groupEn: "Group F", date: "Thứ 6, 26/06/2026", time: "6:00", stadium: "Kansas City Stadium", teamA: "Tunisia", teamAEn: "Tunisia", codeA: "tn", teamB: "Hà Lan", teamBEn: "Netherlands", codeB: "nl", type: "vong-bang" },
    { id: "59", group: "Bảng D", groupEn: "Group D", date: "Thứ 6, 26/06/2026", time: "9:00", stadium: "Los Angeles Stadium", teamA: "Thổ Nhĩ Kỳ", teamAEn: "Turkey", codeA: "tr", teamB: "Mỹ", teamBEn: "USA", codeB: "us", type: "vong-bang" },
    { id: "60", group: "Bảng D", groupEn: "Group D", date: "Thứ 6, 26/06/2026", time: "9:00", stadium: "San Francisco Bay Area Stadium", teamA: "Paraguay", teamAEn: "Paraguay", codeA: "py", teamB: "Australia", teamBEn: "Australia", codeB: "au", type: "vong-bang" },
    { id: "61", group: "Bảng I", groupEn: "Group I", date: "Thứ 7, 27/06/2026", time: "2:00", stadium: "Boston Stadium", teamA: "Na Uy", teamAEn: "Norway", codeA: "no", teamB: "Pháp", teamBEn: "France", codeB: "fr", type: "vong-bang" },
    { id: "62", group: "Bảng I", groupEn: "Group I", date: "Thứ 7, 27/06/2026", time: "2:00", stadium: "Toronto Stadium", teamA: "Senegal", teamAEn: "Senegal", codeA: "sn", teamB: "Iraq", teamBEn: "Iraq", codeB: "iq", type: "vong-bang" },
    { id: "63", group: "Bảng G", groupEn: "Group G", date: "Thứ 7, 27/06/2026", time: "10:00", stadium: "Seattle Stadium", teamA: "Ai Cập", teamAEn: "Egypt", codeA: "eg", teamB: "Iran", teamBEn: "Iran", codeB: "ir", type: "vong-bang" },
    { id: "64", group: "Bảng G", groupEn: "Group G", date: "Thứ 7, 27/06/2026", time: "10:00", stadium: "Vancouver Stadium", teamA: "New Zealand", teamAEn: "New Zealand", codeA: "nz", teamB: "Bỉ", teamBEn: "Belgium", codeB: "be", type: "vong-bang" },
    { id: "65", group: "Bảng H", groupEn: "Group H", date: "Thứ 7, 27/06/2026", time: "7:00", stadium: "Houston Stadium", teamA: "Cape Verde", teamAEn: "Cape Verde", codeA: "cv", teamB: "Ả Rập Xê Út", teamBEn: "Saudi Arabia", codeB: "sa", type: "vong-bang" },
    { id: "66", group: "Bảng H", groupEn: "Group H", date: "Thứ 7, 27/06/2026", time: "7:00", stadium: "Guadalajara Stadium", teamA: "Uruguay", teamAEn: "Uruguay", codeA: "uy", teamB: "Tây Ban Nha", teamBEn: "Spain", codeB: "es", type: "vong-bang" },
    { id: "67", group: "Bảng L", groupEn: "Group L", date: "CN, 28/06/2026", time: "4:00", stadium: "New York/New Jersey Stadium", teamA: "Panama", teamAEn: "Panama", codeA: "pa", teamB: "Anh", teamBEn: "England", codeB: "gb-eng", type: "vong-bang" },
    { id: "68", group: "Bảng L", groupEn: "Group L", date: "CN, 28/06/2026", time: "4:00", stadium: "Philadelphia Stadium", teamA: "Croatia", teamAEn: "Croatia", codeA: "hr", teamB: "Ghana", teamBEn: "Ghana", codeB: "gh", type: "vong-bang" },
    { id: "69", group: "Bảng J", groupEn: "Group J", date: "CN, 28/06/2026", time: "9:00", stadium: "Kansas City Stadium", teamA: "Algeria", teamAEn: "Algeria", codeA: "dz", teamB: "Áo", teamBEn: "Austria", codeB: "at", type: "vong-bang" },
    { id: "70", group: "Bảng J", groupEn: "Group J", date: "CN, 28/06/2026", time: "9:00", stadium: "Dallas Stadium", teamA: "Jordan", teamAEn: "Jordan", codeA: "jo", teamB: "Argentina", teamBEn: "Argentina", codeB: "ar", type: "vong-bang" },
    { id: "71", group: "Bảng K", groupEn: "Group K", date: "CN, 28/06/2026", time: "6:30", stadium: "Miami Stadium", teamA: "Colombia", teamAEn: "Colombia", codeA: "co", teamB: "Bồ Đào Nha", teamBEn: "Portugal", codeB: "pt", type: "vong-bang" },
    { id: "72", group: "Bảng K", groupEn: "Group K", date: "CN, 28/06/2026", time: "6:30", stadium: "Atlanta Stadium", teamA: "Congo", teamAEn: "Congo", codeA: "cg", teamB: "Uzbekistan", teamBEn: "Uzbekistan", codeB: "uz", type: "vong-bang" },
    { id: "73", group: "Vòng 32 Đội", groupEn: "Round of 32", date: "Thứ 2, 29/06/2026", time: "2:00", stadium: "Los Angeles Stadium", teamA: "Nhất Bảng A", teamAEn: "1st Group A", codeA: "placeholder", teamB: "Nhì Bảng B", teamBEn: "2nd Group B", codeB: "placeholder", type: "vong-32" },
    { id: "74", group: "Vòng 32 Đội", groupEn: "Round of 32", date: "Thứ 3, 30/06/2026", time: "3:30", stadium: "Boston Stadium", teamA: "Nhất Bảng E", teamAEn: "1st Group E", codeA: "placeholder", teamB: "Hạng 3 A/B/C/D/F", teamBEn: "3rd A/B/C/D/F", codeB: "placeholder", type: "vong-32" },
    { id: "75", group: "Vòng 32 Đội", groupEn: "Round of 32", date: "Thứ 3, 30/06/2026", time: "8:00", stadium: "Monterrey Stadium", teamA: "Nhất Bảng F", teamAEn: "1st Group F", codeA: "placeholder", teamB: "Nhì Bảng C", teamBEn: "2nd Group C", codeB: "placeholder", type: "vong-32" },
    { id: "76", group: "Vòng 32 Đội", groupEn: "Round of 32", date: "Thứ 3, 30/06/2026", time: "0:00", stadium: "Houston Stadium", teamA: "Nhất Bảng C", teamAEn: "1st Group C", codeA: "placeholder", teamB: "Hạng 3 F/H", teamBEn: "3rd F/H", codeB: "placeholder", type: "vong-32" },
    { id: "77", group: "Vòng 32 Đội", groupEn: "Round of 32", date: "Thứ 4, 01/07/2026", time: "4:00", stadium: "New York/New Jersey Stadium", teamA: "Nhất Bảng I", teamAEn: "1st Group I", codeA: "placeholder", teamB: "Hạng 3 C/D/F/G/H", teamBEn: "3rd C/D/F/G/H", codeB: "placeholder", type: "vong-32" },
    { id: "78", group: "Vòng 32 Đội", groupEn: "Round of 32", date: "Thứ 4, 01/07/2026", time: "8:00", stadium: "Dallas Stadium", teamA: "Nhất Bảng E", teamAEn: "1st Group E", codeA: "placeholder", teamB: "Nhì Bảng I", teamBEn: "2nd Group I", codeB: "placeholder", type: "vong-32" },
    { id: "79", group: "Vòng 32 Đội", groupEn: "Round of 32", date: "Thứ 4, 01/07/2026", time: "8:00", stadium: "Mexico City Stadium", teamA: "Nhất Bảng A", teamAEn: "1st Group A", codeA: "placeholder", teamB: "Hạng 3 C/E/F/H/I", teamBEn: "3rd C/E/F/H/I", codeB: "placeholder", type: "vong-32" },
    { id: "80", group: "Vòng 32 Đội", groupEn: "Round of 32", date: "Thứ 4, 01/07/2026", time: "23:00", stadium: "Atlanta Stadium", teamA: "Nhất Bảng L", teamAEn: "1st Group L", codeA: "placeholder", teamB: "Hạng 3 E/H/I/J/K", teamBEn: "3rd E/H/I/J/K", codeB: "placeholder", type: "vong-32" },
    { id: "81", group: "Vòng 32 Đội", groupEn: "Round of 32", date: "Thứ 5, 02/07/2026", time: "7:00", stadium: "San Francisco Bay Area Stadium", teamA: "Nhất Bảng D", teamAEn: "1st Group D", codeA: "placeholder", teamB: "Hạng 3 B/E/F/I/J", teamBEn: "3rd B/E/F/I/J", codeB: "placeholder", type: "vong-32" },
    { id: "82", group: "Vòng 32 Đội", groupEn: "Round of 32", date: "Thứ 5, 02/07/2026", time: "3:00", stadium: "Seattle Stadium", teamA: "Nhất Bảng G", teamAEn: "1st Group G", codeA: "placeholder", teamB: "Hạng 3 A/E/H/I/J", teamBEn: "3rd A/E/H/I/J", codeB: "placeholder", type: "vong-32" },
    { id: "83", group: "Vòng 32 Đội", groupEn: "Round of 32", date: "Thứ 6, 03/07/2026", time: "6:00", stadium: "Toronto Stadium", teamA: "Nhì Bảng K", teamAEn: "2nd Group K", codeA: "placeholder", teamB: "Nhì Bảng L", teamBEn: "2nd Group L", codeB: "placeholder", type: "vong-32" },
    { id: "84", group: "Vòng 32 Đội", groupEn: "Round of 32", date: "Thứ 6, 03/07/2026", time: "2:00", stadium: "Los Angeles Stadium", teamA: "Nhất Bảng H", teamAEn: "1st Group H", codeA: "placeholder", teamB: "Nhì Bảng J", teamBEn: "2nd Group J", codeB: "placeholder", type: "vong-32" },
    { id: "85", group: "Vòng 32 Đội", groupEn: "Round of 32", date: "Thứ 6, 03/07/2026", time: "10:00", stadium: "Vancouver Stadium", teamA: "Nhất Bảng B", teamAEn: "1st Group B", codeA: "placeholder", teamB: "Hạng 3 E/F/G/I/J", teamBEn: "3rd E/F/G/I/J", codeB: "placeholder", type: "vong-32" },
    { id: "86", group: "Vòng 32 Đội", groupEn: "Round of 32", date: "Thứ 7, 04/07/2026", time: "5:00", stadium: "Miami Stadium", teamA: "Nhất Bảng J", teamAEn: "1st Group J", codeA: "placeholder", teamB: "Nhì Bảng H", teamBEn: "2nd Group H", codeB: "placeholder", type: "vong-32" },
    { id: "87", group: "Vòng 32 Đội", groupEn: "Round of 32", date: "Thứ 7, 04/07/2026", time: "8:30", stadium: "Kansas City Stadium", teamA: "Nhất Bảng K", teamAEn: "1st Group K", codeA: "placeholder", teamB: "Hạng 3 D/E/I/J/L", teamBEn: "3rd D/E/I/J/L", codeB: "placeholder", type: "vong-32" },
    { id: "88", group: "Vòng 32 Đội", groupEn: "Round of 32", date: "Thứ 7, 04/07/2026", time: "1:00", stadium: "Dallas Stadium", teamA: "Nhì Bảng D", teamAEn: "2nd Group D", codeA: "placeholder", teamB: "Nhì Bảng G", teamBEn: "2nd Group G", codeB: "placeholder", type: "vong-32" },
    { id: "89", group: "Vòng 16 Đội", groupEn: "Round of 16", date: "CN, 05/07/2026", time: "4:00", stadium: "Philadelphia Stadium", teamA: "Thắng Trận M74", teamAEn: "Winner M74", codeA: "placeholder", teamB: "Thắng Trận M77", teamBEn: "Winner M77", codeB: "placeholder", type: "vong-16" },
    { id: "90", group: "Vòng 16 Đội", groupEn: "Round of 16", date: "CN, 05/07/2026", time: "0:00", stadium: "Houston Stadium", teamA: "Thắng Trận M73", teamAEn: "Winner M73", codeA: "placeholder", teamB: "Thắng Trận M75", teamBEn: "Winner M75", codeB: "placeholder", type: "vong-16" },
    { id: "91", group: "Vòng 16 Đội", groupEn: "Round of 16", date: "Thứ 2, 06/07/2026", time: "3:00", stadium: "New York/New Jersey Stadium", teamA: "Thắng Trận M76", teamAEn: "Winner M76", codeA: "placeholder", teamB: "Thắng Trận M78", teamBEn: "Winner M78", codeB: "placeholder", type: "vong-16" },
    { id: "92", group: "Vòng 16 Đội", groupEn: "Round of 16", date: "Thứ 2, 06/07/2026", time: "7:00", stadium: "Mexico City Stadium", teamA: "Thắng Trận M79", teamAEn: "Winner M79", codeA: "placeholder", teamB: "Thắng Trận M80", teamBEn: "Winner M80", codeB: "placeholder", type: "vong-16" },
    { id: "93", group: "Vòng 16 Đội", groupEn: "Round of 16", date: "Thứ 3, 07/07/2026", time: "2:00", stadium: "Dallas Stadium", teamA: "Thắng Trận M83", teamAEn: "Winner M83", codeA: "placeholder", teamB: "Thắng Trận M84", teamBEn: "Winner M84", codeB: "placeholder", type: "vong-16" },
    { id: "94", group: "Vòng 16 Đội", groupEn: "Round of 16", date: "Thứ 3, 07/07/2026", time: "7:00", stadium: "Seattle Stadium", teamA: "Thắng Trận M81", teamAEn: "Winner M81", codeA: "placeholder", teamB: "Thắng Trận M82", teamBEn: "Winner M82", codeB: "placeholder", type: "vong-16" },
    { id: "95", group: "Vòng 16 Đội", groupEn: "Round of 16", date: "Thứ 3, 07/07/2026", time: "23:00", stadium: "Atlanta Stadium", teamA: "Thắng Trận M86", teamAEn: "Winner M86", codeA: "placeholder", teamB: "Thắng Trận M88", teamBEn: "Winner M88", codeB: "placeholder", type: "vong-16" },
    { id: "96", group: "Vòng 16 Đội", groupEn: "Round of 16", date: "Thứ 4, 08/07/2026", time: "3:00", stadium: "Vancouver Stadium", teamA: "Thắng Trận M85", teamAEn: "Winner M85", codeA: "placeholder", teamB: "Thắng Trận M87", teamBEn: "Winner M87", codeB: "placeholder", type: "vong-16" },
    { id: "97", group: "Tứ Kết 1", groupEn: "Quarter-Finals 1", date: "Thứ 6, 10/07/2026", time: "3:00", stadium: "Boston Stadium", teamA: "Thắng Trận M89", teamAEn: "Winner M89", codeA: "placeholder", teamB: "Thắng Trận M90", teamBEn: "Winner M90", codeB: "placeholder", type: "tu-ket" },
    { id: "98", group: "Tứ Kết 2", groupEn: "Quarter-Finals 2", date: "Thứ 7, 11/07/2026", time: "2:00", stadium: "Los Angeles Stadium", teamA: "Thắng Trận M93", teamAEn: "Winner M93", codeA: "placeholder", teamB: "Thắng Trận M94", teamBEn: "Winner M94", codeB: "placeholder", type: "tu-ket" },
    { id: "99", group: "Tứ Kết 3", groupEn: "Quarter-Finals 3", date: "CN, 12/07/2026", time: "4:00", stadium: "Miami Stadium", teamA: "Thắng Trận M91", teamAEn: "Winner M91", codeA: "placeholder", teamB: "Thắng Trận M92", teamBEn: "Winner M92", codeB: "placeholder", type: "tu-ket" },
    { id: "100", group: "Tứ Kết 4", groupEn: "Quarter-Finals 4", date: "CN, 12/07/2026", time: "8:00", stadium: "Kansas City Stadium", teamA: "Thắng Trận M95", teamAEn: "Winner M95", codeA: "placeholder", teamB: "Thắng Trận M96", teamBEn: "Winner M96", codeB: "placeholder", type: "tu-ket" },
    { id: "101", group: "Bán Kết 1", groupEn: "Semi-Finals 1", date: "Thứ 4, 15/07/2026", time: "2:00", stadium: "Dallas Stadium", teamA: "Thắng Trận M97", teamAEn: "Winner M97", codeA: "placeholder", teamB: "Thắng Trận M98", teamBEn: "Winner M98", codeB: "placeholder", type: "ban-ket" },
    { id: "102", group: "Bán Kết 2", groupEn: "Semi-Finals 2", date: "Thứ 5, 16/07/2026", time: "2:00", stadium: "Atlanta Stadium", teamA: "Thắng Trận M99", teamAEn: "Winner M99", codeA: "placeholder", teamB: "Thắng Trận M100", teamBEn: "Winner M100", codeB: "placeholder", type: "ban-ket" },
    { id: "103", group: "Tranh Hạng 3", groupEn: "Third Place Playoff", date: "CN, 19/07/2026", time: "4:00", stadium: "Miami Stadium", teamA: "Thua Trận M101", teamAEn: "Loser M101", codeA: "placeholder", teamB: "Thua Trận M102", teamBEn: "Loser M102", codeB: "placeholder", type: "chung-ket" },
    { id: "104", group: "Chung Kết Tổng", groupEn: "World Cup Grand Final", date: "Thứ 2, 20/07/2026", time: "2:00", stadium: "New York/New Jersey Stadium", teamA: "Thắng Trận M101", teamAEn: "Winner M101", codeA: "placeholder", teamB: "Thắng Trận M102", teamBEn: "Winner M102", codeB: "placeholder", type: "chung-ket" }
];

// Đồng bộ với app-logic.js
window.userPredictionMemory = window.userPredictionMemory || [];
